console.log(`== System ==`)
console.log(`platform: ${process.platform}`)
console.log(`architecture: ${process.arch}`)
console.log(`\n== NodeJS ==`)
console.log(`node version: ${process.version}`)
console.log(`v8 version: ${process.versions.v8}`)
console.log(`libuv version: ${process.versions.libuv}`)
console.log(`== Process ==`)
console.log(`pid: ${process.pid}`)
console.log(`title: ${process.title}`)
const folder = process.cwd()
console.log(`Current Working Directory: ${folder}`)